coverage:
  precision: 2
  round: down
  range: "70...100"


parser:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no


ignore:
  - "services/cli/"
