language: c
compiler: gcc clang
before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler libprotobuf-dev libprotoc-dev

script:
  - bash build.sh run_gcc_tests clang
  - bash build.sh run_gcc_tests

after_success:
  - pip install --user cpp-coveralls
  - coveralls --exclude gpslib/src/tests/ --exclude logsrv/tests/  --exclude tests/ --gcov-options '\-lp'
