language: c
compiler: gcc clang
before_install:
  - pip install --user cpp-coveralls

script:
  - bash build.sh run_gcc_tests clang
  - bash build.sh run_gcc_tests

after_success:
  - pip install --user cpp-coveralls
  - coveralls --exclude build/ --exclude tests/ --gcov-options '\-lp'
