language: c
compiler: gcc clang
before_install:
  - pip install --user cpp-coveralls
  - git clone https://github.com/protocolbuffers/protobuf.git
  - cd protobuf
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - git clone https://github.com/protobuf-c/protobuf-c.git
  - cd protobuf-c
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install

script:
  - bash build.sh run_gcc_tests clang
  - bash build.sh run_gcc_tests

after_success:
  - pip install --user cpp-coveralls
  - coveralls --exclude gpslib/src/tests/ --exclude logsrv/tests/  --exclude tests/ --gcov-options '\-lp'
