language: c
compiler: gcc clang
before_install:
  - pip install --user cpp-coveralls
  - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
  - sudo apt-get update -qq
  # We have to install protoc, and python libs for both python and python3, since mypy runs py3
  - sudo apt-get install -qq protobuf-compiler python-protobuf python3-protobuf python3 python3-pip
  - git clone https://github.com/protobuf-c/protobuf-c.git
  - ./autogen.sh
  - ./configure
  - sudo make 
  - sudo make install

script:
  - bash build.sh run_gcc_tests clang
  - bash build.sh run_gcc_tests

after_success:
  - pip install --user cpp-coveralls
  - coveralls --exclude gpslib/src/tests/ --exclude logsrv/tests/  --exclude tests/ --gcov-options '\-lp'
