/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ota_comm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ota_comm.pb-c.h"
void   ota_key_valdata__init
                     (OtaKeyValdata         *message)
{
  static OtaKeyValdata init_value = OTA_KEY_VALDATA__INIT;
  *message = init_value;
}
size_t ota_key_valdata__get_packed_size
                     (const OtaKeyValdata *message)
{
  assert(message->base.descriptor == &ota_key_valdata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_key_valdata__pack
                     (const OtaKeyValdata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_key_valdata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_key_valdata__pack_to_buffer
                     (const OtaKeyValdata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_key_valdata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaKeyValdata *
       ota_key_valdata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaKeyValdata *)
     protobuf_c_message_unpack (&ota_key_valdata__descriptor,
                                allocator, len, data);
}
void   ota_key_valdata__free_unpacked
                     (OtaKeyValdata *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_key_valdata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message_poll__init
                     (OtaMessagePoll         *message)
{
  static OtaMessagePoll init_value = OTA_MESSAGE_POLL__INIT;
  *message = init_value;
}
size_t ota_message_poll__get_packed_size
                     (const OtaMessagePoll *message)
{
  assert(message->base.descriptor == &ota_message_poll__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message_poll__pack
                     (const OtaMessagePoll *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message_poll__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message_poll__pack_to_buffer
                     (const OtaMessagePoll *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message_poll__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessagePoll *
       ota_message_poll__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessagePoll *)
     protobuf_c_message_unpack (&ota_message_poll__descriptor,
                                allocator, len, data);
}
void   ota_message_poll__free_unpacked
                     (OtaMessagePoll *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message_poll__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message_poll_resp__ota_gmtime__init
                     (OtaMessagePollResp__OtaGmtime         *message)
{
  static OtaMessagePollResp__OtaGmtime init_value = OTA_MESSAGE_POLL_RESP__OTA_GMTIME__INIT;
  *message = init_value;
}
void   ota_message_poll_resp__init
                     (OtaMessagePollResp         *message)
{
  static OtaMessagePollResp init_value = OTA_MESSAGE_POLL_RESP__INIT;
  *message = init_value;
}
size_t ota_message_poll_resp__get_packed_size
                     (const OtaMessagePollResp *message)
{
  assert(message->base.descriptor == &ota_message_poll_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message_poll_resp__pack
                     (const OtaMessagePollResp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message_poll_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message_poll_resp__pack_to_buffer
                     (const OtaMessagePollResp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message_poll_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessagePollResp *
       ota_message_poll_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessagePollResp *)
     protobuf_c_message_unpack (&ota_message_poll_resp__descriptor,
                                allocator, len, data);
}
void   ota_message_poll_resp__free_unpacked
                     (OtaMessagePollResp *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message_poll_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message_tsfr_hook__init
                     (OtaMessageTsfrHook         *message)
{
  static OtaMessageTsfrHook init_value = OTA_MESSAGE_TSFR_HOOK__INIT;
  *message = init_value;
}
size_t ota_message_tsfr_hook__get_packed_size
                     (const OtaMessageTsfrHook *message)
{
  assert(message->base.descriptor == &ota_message_tsfr_hook__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message_tsfr_hook__pack
                     (const OtaMessageTsfrHook *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message_tsfr_hook__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message_tsfr_hook__pack_to_buffer
                     (const OtaMessageTsfrHook *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message_tsfr_hook__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessageTsfrHook *
       ota_message_tsfr_hook__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessageTsfrHook *)
     protobuf_c_message_unpack (&ota_message_tsfr_hook__descriptor,
                                allocator, len, data);
}
void   ota_message_tsfr_hook__free_unpacked
                     (OtaMessageTsfrHook *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message_tsfr_hook__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message_tsfr__init
                     (OtaMessageTsfr         *message)
{
  static OtaMessageTsfr init_value = OTA_MESSAGE_TSFR__INIT;
  *message = init_value;
}
size_t ota_message_tsfr__get_packed_size
                     (const OtaMessageTsfr *message)
{
  assert(message->base.descriptor == &ota_message_tsfr__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message_tsfr__pack
                     (const OtaMessageTsfr *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message_tsfr__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message_tsfr__pack_to_buffer
                     (const OtaMessageTsfr *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message_tsfr__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessageTsfr *
       ota_message_tsfr__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessageTsfr *)
     protobuf_c_message_unpack (&ota_message_tsfr__descriptor,
                                allocator, len, data);
}
void   ota_message_tsfr__free_unpacked
                     (OtaMessageTsfr *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message_tsfr__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message_tsfr_ack__init
                     (OtaMessageTsfrAck         *message)
{
  static OtaMessageTsfrAck init_value = OTA_MESSAGE_TSFR_ACK__INIT;
  *message = init_value;
}
size_t ota_message_tsfr_ack__get_packed_size
                     (const OtaMessageTsfrAck *message)
{
  assert(message->base.descriptor == &ota_message_tsfr_ack__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message_tsfr_ack__pack
                     (const OtaMessageTsfrAck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message_tsfr_ack__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message_tsfr_ack__pack_to_buffer
                     (const OtaMessageTsfrAck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message_tsfr_ack__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessageTsfrAck *
       ota_message_tsfr_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessageTsfrAck *)
     protobuf_c_message_unpack (&ota_message_tsfr_ack__descriptor,
                                allocator, len, data);
}
void   ota_message_tsfr_ack__free_unpacked
                     (OtaMessageTsfrAck *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message_tsfr_ack__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message_tsfr_query__init
                     (OtaMessageTsfrQuery         *message)
{
  static OtaMessageTsfrQuery init_value = OTA_MESSAGE_TSFR_QUERY__INIT;
  *message = init_value;
}
size_t ota_message_tsfr_query__get_packed_size
                     (const OtaMessageTsfrQuery *message)
{
  assert(message->base.descriptor == &ota_message_tsfr_query__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message_tsfr_query__pack
                     (const OtaMessageTsfrQuery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message_tsfr_query__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message_tsfr_query__pack_to_buffer
                     (const OtaMessageTsfrQuery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message_tsfr_query__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessageTsfrQuery *
       ota_message_tsfr_query__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessageTsfrQuery *)
     protobuf_c_message_unpack (&ota_message_tsfr_query__descriptor,
                                allocator, len, data);
}
void   ota_message_tsfr_query__free_unpacked
                     (OtaMessageTsfrQuery *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message_tsfr_query__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota_message__init
                     (OtaMessage         *message)
{
  static OtaMessage init_value = OTA_MESSAGE__INIT;
  *message = init_value;
}
size_t ota_message__get_packed_size
                     (const OtaMessage *message)
{
  assert(message->base.descriptor == &ota_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota_message__pack
                     (const OtaMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota_message__pack_to_buffer
                     (const OtaMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OtaMessage *
       ota_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OtaMessage *)
     protobuf_c_message_unpack (&ota_message__descriptor,
                                allocator, len, data);
}
void   ota_message__free_unpacked
                     (OtaMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ota_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ota_key_valdata__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OtaKeyValdata, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OtaKeyValdata, val),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_key_valdata__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange ota_key_valdata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ota_key_valdata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_key_valdata",
  "OtaKeyValdata",
  "OtaKeyValdata",
  "",
  sizeof(OtaKeyValdata),
  2,
  ota_key_valdata__field_descriptors,
  ota_key_valdata__field_indices_by_name,
  1,  ota_key_valdata__number_ranges,
  (ProtobufCMessageInit) ota_key_valdata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_message_poll__field_descriptors[11] =
{
  {
    "myversion_x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, myversion_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myversion_y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, myversion_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myversion_z",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, myversion_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "myversion_w",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, myversion_w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceid",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mfgdate",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, mfgdate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hwrev",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, hwrev),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cur_disk_used",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, cur_disk_used),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "free_disk",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePoll, free_disk),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hwcaps",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OtaMessagePoll, n_hwcaps),
    offsetof(OtaMessagePoll, hwcaps),
    &ota_key_valdata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "swcaps",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(OtaMessagePoll, n_swcaps),
    offsetof(OtaMessagePoll, swcaps),
    &ota_key_valdata__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_poll__field_indices_by_name[] = {
  7,   /* field[7] = cur_disk_used */
  4,   /* field[4] = deviceid */
  8,   /* field[8] = free_disk */
  9,   /* field[9] = hwcaps */
  6,   /* field[6] = hwrev */
  5,   /* field[5] = mfgdate */
  3,   /* field[3] = myversion_w */
  0,   /* field[0] = myversion_x */
  1,   /* field[1] = myversion_y */
  2,   /* field[2] = myversion_z */
  10,   /* field[10] = swcaps */
};
static const ProtobufCIntRange ota_message_poll__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor ota_message_poll__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_poll",
  "OtaMessagePoll",
  "OtaMessagePoll",
  "",
  sizeof(OtaMessagePoll),
  11,
  ota_message_poll__field_descriptors,
  ota_message_poll__field_indices_by_name,
  1,  ota_message_poll__number_ranges,
  (ProtobufCMessageInit) ota_message_poll__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_message_poll_resp__ota_gmtime__field_descriptors[6] =
{
  {
    "year",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp__OtaGmtime, year),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "month",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp__OtaGmtime, month),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "day",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp__OtaGmtime, day),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hour",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp__OtaGmtime, hour),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "min",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp__OtaGmtime, min),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sec",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp__OtaGmtime, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_poll_resp__ota_gmtime__field_indices_by_name[] = {
  2,   /* field[2] = day */
  3,   /* field[3] = hour */
  4,   /* field[4] = min */
  1,   /* field[1] = month */
  5,   /* field[5] = sec */
  0,   /* field[0] = year */
};
static const ProtobufCIntRange ota_message_poll_resp__ota_gmtime__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ota_message_poll_resp__ota_gmtime__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_poll_resp.ota_gmtime",
  "OtaGmtime",
  "OtaMessagePollResp__OtaGmtime",
  "",
  sizeof(OtaMessagePollResp__OtaGmtime),
  6,
  ota_message_poll_resp__ota_gmtime__field_descriptors,
  ota_message_poll_resp__ota_gmtime__field_indices_by_name,
  1,  ota_message_poll_resp__ota_gmtime__number_ranges,
  (ProtobufCMessageInit) ota_message_poll_resp__ota_gmtime__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ota_message_poll_resp__ota_poll_status__enum_values_by_number[3] =
{
  { "OTA_POLL_STATUS_OK", "OTA_MESSAGE_POLL_RESP__OTA_POLL_STATUS__OTA_POLL_STATUS_OK", 1 },
  { "OTA_POLL_INVALID_DEVICE_ID", "OTA_MESSAGE_POLL_RESP__OTA_POLL_STATUS__OTA_POLL_INVALID_DEVICE_ID", 2 },
  { "OTA_POLL_STATUS_RESRVED", "OTA_MESSAGE_POLL_RESP__OTA_POLL_STATUS__OTA_POLL_STATUS_RESRVED", 255 },
};
static const ProtobufCIntRange ota_message_poll_resp__ota_poll_status__value_ranges[] = {
{1, 0},{255, 2},{0, 3}
};
static const ProtobufCEnumValueIndex ota_message_poll_resp__ota_poll_status__enum_values_by_name[3] =
{
  { "OTA_POLL_INVALID_DEVICE_ID", 1 },
  { "OTA_POLL_STATUS_OK", 0 },
  { "OTA_POLL_STATUS_RESRVED", 2 },
};
const ProtobufCEnumDescriptor ota_message_poll_resp__ota_poll_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ota_message_poll_resp.ota_poll_status",
  "ota_poll_status",
  "OtaMessagePollResp__OtaPollStatus",
  "",
  3,
  ota_message_poll_resp__ota_poll_status__enum_values_by_number,
  3,
  ota_message_poll_resp__ota_poll_status__enum_values_by_name,
  2,
  ota_message_poll_resp__ota_poll_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ota_message_poll_resp__ota_enc_alg__enum_values_by_number[3] =
{
  { "OTA_ENC_ALG_AES_128", "OTA_MESSAGE_POLL_RESP__OTA_ENC_ALG__OTA_ENC_ALG_AES_128", 1 },
  { "OTA_ENC_ALG_AES_256", "OTA_MESSAGE_POLL_RESP__OTA_ENC_ALG__OTA_ENC_ALG_AES_256", 2 },
  { "OTA_ENC_ALG_INVALID", "OTA_MESSAGE_POLL_RESP__OTA_ENC_ALG__OTA_ENC_ALG_INVALID", 255 },
};
static const ProtobufCIntRange ota_message_poll_resp__ota_enc_alg__value_ranges[] = {
{1, 0},{255, 2},{0, 3}
};
static const ProtobufCEnumValueIndex ota_message_poll_resp__ota_enc_alg__enum_values_by_name[3] =
{
  { "OTA_ENC_ALG_AES_128", 0 },
  { "OTA_ENC_ALG_AES_256", 1 },
  { "OTA_ENC_ALG_INVALID", 2 },
};
const ProtobufCEnumDescriptor ota_message_poll_resp__ota_enc_alg__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ota_message_poll_resp.ota_enc_alg",
  "ota_enc_alg",
  "OtaMessagePollResp__OtaEncAlg",
  "",
  3,
  ota_message_poll_resp__ota_enc_alg__enum_values_by_number,
  3,
  ota_message_poll_resp__ota_enc_alg__enum_values_by_name,
  2,
  ota_message_poll_resp__ota_enc_alg__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue ota_message_poll_resp__ota_sign_alg__enum_values_by_number[3] =
{
  { "OTA_SIGN_ALG_ECC_256", "OTA_MESSAGE_POLL_RESP__OTA_SIGN_ALG__OTA_SIGN_ALG_ECC_256", 1 },
  { "OTA_SIGN_ALG_RSA_4096", "OTA_MESSAGE_POLL_RESP__OTA_SIGN_ALG__OTA_SIGN_ALG_RSA_4096", 2 },
  { "OTA_SIGN_ALG_INVALID", "OTA_MESSAGE_POLL_RESP__OTA_SIGN_ALG__OTA_SIGN_ALG_INVALID", 255 },
};
static const ProtobufCIntRange ota_message_poll_resp__ota_sign_alg__value_ranges[] = {
{1, 0},{255, 2},{0, 3}
};
static const ProtobufCEnumValueIndex ota_message_poll_resp__ota_sign_alg__enum_values_by_name[3] =
{
  { "OTA_SIGN_ALG_ECC_256", 0 },
  { "OTA_SIGN_ALG_INVALID", 2 },
  { "OTA_SIGN_ALG_RSA_4096", 1 },
};
const ProtobufCEnumDescriptor ota_message_poll_resp__ota_sign_alg__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ota_message_poll_resp.ota_sign_alg",
  "ota_sign_alg",
  "OtaMessagePollResp__OtaSignAlg",
  "",
  3,
  ota_message_poll_resp__ota_sign_alg__enum_values_by_number,
  3,
  ota_message_poll_resp__ota_sign_alg__enum_values_by_name,
  2,
  ota_message_poll_resp__ota_sign_alg__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ota_message_poll_resp__field_descriptors[13] =
{
  {
    "deviceid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota_resp_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, ota_resp_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, status),
    &ota_message_poll_resp__ota_poll_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_available",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, update_available),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newver_x",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, newver_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newver_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, newver_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newver_z",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, newver_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newver_w",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, newver_w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_name",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, firmware_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "created_timestamp",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, created_timestamp),
    &ota_message_poll_resp__ota_gmtime__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "update_size_bytes",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, update_size_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enc_alg",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, enc_alg),
    &ota_message_poll_resp__ota_enc_alg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sign_alg",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OtaMessagePollResp, sign_alg),
    &ota_message_poll_resp__ota_sign_alg__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_poll_resp__field_indices_by_name[] = {
  9,   /* field[9] = created_timestamp */
  0,   /* field[0] = deviceid */
  11,   /* field[11] = enc_alg */
  8,   /* field[8] = firmware_name */
  7,   /* field[7] = newver_w */
  4,   /* field[4] = newver_x */
  5,   /* field[5] = newver_y */
  6,   /* field[6] = newver_z */
  1,   /* field[1] = ota_resp_hash */
  12,   /* field[12] = sign_alg */
  2,   /* field[2] = status */
  3,   /* field[3] = update_available */
  10,   /* field[10] = update_size_bytes */
};
static const ProtobufCIntRange ota_message_poll_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor ota_message_poll_resp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_poll_resp",
  "OtaMessagePollResp",
  "OtaMessagePollResp",
  "",
  sizeof(OtaMessagePollResp),
  13,
  ota_message_poll_resp__field_descriptors,
  ota_message_poll_resp__field_indices_by_name,
  1,  ota_message_poll_resp__number_ranges,
  (ProtobufCMessageInit) ota_message_poll_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_message_tsfr_hook__field_descriptors[5] =
{
  {
    "deviceid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrHook, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota_resp_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrHook, ota_resp_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sends_ack",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrHook, sends_ack),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack_repeat_rate",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrHook, ack_repeat_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txbuf_size",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrHook, txbuf_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_tsfr_hook__field_indices_by_name[] = {
  3,   /* field[3] = ack_repeat_rate */
  0,   /* field[0] = deviceid */
  1,   /* field[1] = ota_resp_hash */
  2,   /* field[2] = sends_ack */
  4,   /* field[4] = txbuf_size */
};
static const ProtobufCIntRange ota_message_tsfr_hook__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor ota_message_tsfr_hook__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_tsfr_hook",
  "OtaMessageTsfrHook",
  "OtaMessageTsfrHook",
  "",
  sizeof(OtaMessageTsfrHook),
  5,
  ota_message_tsfr_hook__field_descriptors,
  ota_message_tsfr_hook__field_indices_by_name,
  1,  ota_message_tsfr_hook__number_ranges,
  (ProtobufCMessageInit) ota_message_tsfr_hook__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_message_tsfr__field_descriptors[4] =
{
  {
    "deviceid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfr, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota_resp_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfr, ota_resp_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seqnum",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfr, seqnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfr, payload),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_tsfr__field_indices_by_name[] = {
  0,   /* field[0] = deviceid */
  1,   /* field[1] = ota_resp_hash */
  3,   /* field[3] = payload */
  2,   /* field[2] = seqnum */
};
static const ProtobufCIntRange ota_message_tsfr__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ota_message_tsfr__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_tsfr",
  "OtaMessageTsfr",
  "OtaMessageTsfr",
  "",
  sizeof(OtaMessageTsfr),
  4,
  ota_message_tsfr__field_descriptors,
  ota_message_tsfr__field_indices_by_name,
  1,  ota_message_tsfr__number_ranges,
  (ProtobufCMessageInit) ota_message_tsfr__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_message_tsfr_ack__field_descriptors[2] =
{
  {
    "deviceid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrAck, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota_resp_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrAck, ota_resp_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_tsfr_ack__field_indices_by_name[] = {
  0,   /* field[0] = deviceid */
  1,   /* field[1] = ota_resp_hash */
};
static const ProtobufCIntRange ota_message_tsfr_ack__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ota_message_tsfr_ack__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_tsfr_ack",
  "OtaMessageTsfrAck",
  "OtaMessageTsfrAck",
  "",
  sizeof(OtaMessageTsfrAck),
  2,
  ota_message_tsfr_ack__field_descriptors,
  ota_message_tsfr_ack__field_indices_by_name,
  1,  ota_message_tsfr_ack__number_ranges,
  (ProtobufCMessageInit) ota_message_tsfr_ack__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota_message_tsfr_query__field_descriptors[3] =
{
  {
    "deviceid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrQuery, deviceid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ota_resp_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrQuery, ota_resp_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seqnum",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(OtaMessageTsfrQuery, seqnum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message_tsfr_query__field_indices_by_name[] = {
  0,   /* field[0] = deviceid */
  1,   /* field[1] = ota_resp_hash */
  2,   /* field[2] = seqnum */
};
static const ProtobufCIntRange ota_message_tsfr_query__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ota_message_tsfr_query__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message_tsfr_query",
  "OtaMessageTsfrQuery",
  "OtaMessageTsfrQuery",
  "",
  sizeof(OtaMessageTsfrQuery),
  3,
  ota_message_tsfr_query__field_descriptors,
  ota_message_tsfr_query__field_indices_by_name,
  1,  ota_message_tsfr_query__number_ranges,
  (ProtobufCMessageInit) ota_message_tsfr_query__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue ota_message__ota_proto_types__enum_values_by_number[6] =
{
  { "OTA_MESSAGE_POLL", "OTA_MESSAGE__OTA_PROTO_TYPES__OTA_MESSAGE_POLL", 1 },
  { "OTA_MESSAGE_POLL_RESP", "OTA_MESSAGE__OTA_PROTO_TYPES__OTA_MESSAGE_POLL_RESP", 2 },
  { "OTA_MESSAGE_TSFR_HOOK", "OTA_MESSAGE__OTA_PROTO_TYPES__OTA_MESSAGE_TSFR_HOOK", 3 },
  { "OTA_MESSAGE_TSFR_QUERY", "OTA_MESSAGE__OTA_PROTO_TYPES__OTA_MESSAGE_TSFR_QUERY", 4 },
  { "OTA_MESSAGE_TSFR", "OTA_MESSAGE__OTA_PROTO_TYPES__OTA_MESSAGE_TSFR", 5 },
  { "OTA_MESSAGE_TSFR_ACK", "OTA_MESSAGE__OTA_PROTO_TYPES__OTA_MESSAGE_TSFR_ACK", 6 },
};
static const ProtobufCIntRange ota_message__ota_proto_types__value_ranges[] = {
{1, 0},{0, 6}
};
static const ProtobufCEnumValueIndex ota_message__ota_proto_types__enum_values_by_name[6] =
{
  { "OTA_MESSAGE_POLL", 0 },
  { "OTA_MESSAGE_POLL_RESP", 1 },
  { "OTA_MESSAGE_TSFR", 4 },
  { "OTA_MESSAGE_TSFR_ACK", 5 },
  { "OTA_MESSAGE_TSFR_HOOK", 2 },
  { "OTA_MESSAGE_TSFR_QUERY", 3 },
};
const ProtobufCEnumDescriptor ota_message__ota_proto_types__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ota_message.ota_proto_types",
  "ota_proto_types",
  "OtaMessage__OtaProtoTypes",
  "",
  6,
  ota_message__ota_proto_types__enum_values_by_number,
  6,
  ota_message__ota_proto_types__enum_values_by_name,
  1,
  ota_message__ota_proto_types__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor ota_message__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, type),
    &ota_message__ota_proto_types__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poll",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, poll),
    &ota_message_poll__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "poll_resp",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, poll_resp),
    &ota_message_poll_resp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tsfr_hook",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, tsfr_hook),
    &ota_message_tsfr_hook__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tsfr_msg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, tsfr_msg),
    &ota_message_tsfr__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ack",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, ack),
    &ota_message_tsfr_ack__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "query",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(OtaMessage, query),
    &ota_message_tsfr_query__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota_message__field_indices_by_name[] = {
  5,   /* field[5] = ack */
  1,   /* field[1] = poll */
  2,   /* field[2] = poll_resp */
  6,   /* field[6] = query */
  3,   /* field[3] = tsfr_hook */
  4,   /* field[4] = tsfr_msg */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange ota_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor ota_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota_message",
  "OtaMessage",
  "OtaMessage",
  "",
  sizeof(OtaMessage),
  7,
  ota_message__field_descriptors,
  ota_message__field_indices_by_name,
  1,  ota_message__number_ranges,
  (ProtobufCMessageInit) ota_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
