#ifndef __EDGE_OS_ERROR_CODES_H__
#define __EDGE_OS_ERROR_CODES_H__

typedef enum {
    EDGEOS_SUCCESS,
    EDGEOS_ESOCK_OPEN_FAIL = -1,
    EDGEOS_EBIND_FAILURE = -2,
    EDGEOS_ECONN_FAILURE = -3,
    EDGEOS_ECONN_REFUSED = -4,
    EDGEOS_EACCEPT_FAILURE = -5,
    EDGEOS_EINVAL = -6,
    EDGEOS_EUNKNOWN = -65535,
} edgeos_errcode_t;

#endif

